// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpcglfuzylcgdtgivdtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwY2dsZnV6eWxjZ2R0Z2l2ZHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODUzMjEsImV4cCI6MjA3MjA2MTMyMX0.KXwEQCR8hrgCFo3ya2vaddMdOyX2jcNwjnS6Xt77PDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});